# Generated by Django 4.1.4 on 2023-01-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_categorieannonce_annonce_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='surface',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
