# Generated by Django 4.1.4 on 2023-01-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_prix_annonce_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annonces.contact'),
            preserve_default=False,
        ),
    ]
