# Generated by Django 4.1.4 on 2023-02-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_annonce_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nom',
            new_name='name',
        ),
    ]
