# Generated by Django 4.1.4 on 2023-02-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_rename_nom_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='username',
        ),
        migrations.AddField(
            model_name='annonce',
            name='loc1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='loc2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
