# Generated by Django 4.1.4 on 2023-02-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_rename_mail_contact_username_annonce_loc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepteur', models.CharField(max_length=200)),
                ('emetteur', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
