# Generated by Django 4.1.4 on 2023-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='commune',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='wilaya',
            field=models.CharField(max_length=200),
        ),
    ]
