# Generated by Django 4.1.4 on 2023-02-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('annonces', '0009_alter_bienimmobilier_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.commune'),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.wilaya'),
        ),
    ]
